# Generated by Django 5.2.1 on 2025-06-04 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.language')),
                ('parents', models.ManyToManyField(blank=True, to='entities.learninggoal')),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_context', models.TextField(default='Unknown')),
                ('license', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('owner_link', models.URLField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.language')),
                ('learning_goals', models.ManyToManyField(blank=True, to='entities.learninggoal')),
                ('translations', models.ManyToManyField(blank=True, to='entities.unitofmeaning')),
            ],
        ),
    ]
