# Generated by Django 5.2.1 on 2025-06-02 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='learninggoal',
            name='parents',
            field=models.ManyToManyField(blank=True, to='entities.learninggoal'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.ImageField(upload_to='templates/images/')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.template')),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'template')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.URLField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.template')),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'template')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldTargetLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.template')),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'template')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.template')),
            ],
            options={
                'abstract': False,
                'unique_together': {('key', 'template')},
            },
        ),
    ]
