# Generated by Django 5.2.1 on 2025-06-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learninggoal',
            options={'ordering': ['-updated_at', 'name']},
        ),
        migrations.AlterModelOptions(
            name='unitofmeaning',
            options={'ordering': ['-updated_at', 'text']},
        ),
        migrations.AlterField(
            model_name='learninggoal',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='entities.learninggoal'),
        ),
    ]
