# Generated by Django 5.2.1 on 2025-06-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_learninggoal_parents_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='content',
        ),
        migrations.RemoveField(
            model_name='template',
            name='name',
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.learninggoal'),
        ),
        migrations.AddField(
            model_name='template',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.template'),
        ),
        migrations.AddField(
            model_name='templatefieldimage',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.templatefieldimage'),
        ),
        migrations.AddField(
            model_name='templatefieldlink',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.templatefieldlink'),
        ),
        migrations.AddField(
            model_name='templatefieldtargetlanguage',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.templatefieldtargetlanguage'),
        ),
        migrations.AddField(
            model_name='templatefieldtranslation',
            name='derived_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entities.templatefieldtranslation'),
        ),
    ]
