# Generated by Django 5.2.1 on 2025-06-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_alter_learninggoal_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeaning',
            name='pronunciation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
