# Generated by Django 5.2.1 on 2025-06-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_unitofmeaning_pronunciation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learninggoal',
            name='language',
        ),
        migrations.RemoveField(
            model_name='unitofmeaning',
            name='language',
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='language_code',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeaning',
            name='language_code',
            field=models.CharField(default='unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
