# Generated by Django 5.2.1 on 2025-06-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_learninggoal_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeaning',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unitofmeaning',
            name='type_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='learninggoal',
            unique_together={('language_code', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeaning',
            unique_together={('text', 'language_code', 'type_info')},
        ),
    ]
