# Generated by Django 5.2.1 on 2025-06-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_language_learninggoal_language_template_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='learning_goals',
            field=models.ManyToManyField(to='entities.learninggoal'),
        ),
    ]
