# Generated by Django 5.2.1 on 2025-06-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_unitofmeaning_notes_unitofmeaning_type_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeaning',
            name='similar_but_not_synonyms',
            field=models.ManyToManyField(blank=True, to='entities.unitofmeaning'),
        ),
        migrations.AddField(
            model_name='unitofmeaning',
            name='synonyms',
            field=models.ManyToManyField(blank=True, to='entities.unitofmeaning'),
        ),
    ]
