# Generated by Django 5.2.1 on 2025-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_artifact'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='templatefieldlink',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatefieldlink',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='templatefieldlink',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='templatefieldtargetlanguage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatefieldtargetlanguage',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='templatefieldtargetlanguage',
            name='template',
        ),
        migrations.AlterUniqueTogether(
            name='templatefieldtranslation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='templatefieldtranslation',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='templatefieldtranslation',
            name='template',
        ),
        migrations.AddField(
            model_name='template',
            name='field_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='template',
            name='field_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='field_target_language',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='field_translation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='TemplateFieldImage',
        ),
        migrations.DeleteModel(
            name='TemplateFieldLink',
        ),
        migrations.DeleteModel(
            name='TemplateFieldTargetLanguage',
        ),
        migrations.DeleteModel(
            name='TemplateFieldTranslation',
        ),
    ]
