# Generated by Django 5.2.1 on 2025-06-05 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_unitofmeaning_similar_but_not_synonyms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_context', models.TextField(default='Unknown')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='entities.learningunit')),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
                'unique_together': {('language_code', 'name')},
            },
        ),
        migrations.RemoveField(
            model_name='unitofmeaning',
            name='learning_goals',
        ),
        migrations.AlterUniqueTogether(
            name='unitofmeaning',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='unitofmeaning',
            name='similar_but_not_synonyms',
        ),
        migrations.RemoveField(
            model_name='unitofmeaning',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='unitofmeaning',
            name='translations',
        ),
        migrations.CreateModel(
            name='TanglibleLearningUnit',
            fields=[
                ('learningunit_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.learningunit')),
                ('text', models.TextField()),
                ('pronunciation', models.TextField(blank=True, null=True)),
                ('type_info', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('license', models.TextField(blank=True, null=True)),
                ('owner', models.TextField(blank=True, null=True)),
                ('owner_link', models.URLField(blank=True, null=True)),
                ('source', models.TextField(blank=True, null=True)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('similar_but_not_synonyms', models.ManyToManyField(blank=True, to='entities.tangliblelearningunit')),
                ('synonyms', models.ManyToManyField(blank=True, to='entities.tangliblelearningunit')),
                ('translations', models.ManyToManyField(blank=True, to='entities.tangliblelearningunit')),
            ],
            options={
                'ordering': ['-updated_at', 'text'],
                'unique_together': {('text', 'type_info')},
            },
            bases=('entities.learningunit',),
        ),
        migrations.DeleteModel(
            name='LearningGoal',
        ),
        migrations.DeleteModel(
            name='UnitOfMeaning',
        ),
    ]
