# Generated by Django 5.2.1 on 2025-06-03 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_templatefieldlink_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='template',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='template',
            name='language',
        ),
        migrations.RemoveField(
            model_name='template',
            name='learning_goals',
        ),
        migrations.RemoveField(
            model_name='language',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='language',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='derived_from',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='learninggoal',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='UnitOfMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unit_of_meaning_images/')),
                ('learning_goals', models.ManyToManyField(blank=True, to='entities.learninggoal')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.language')),
                ('unit_of_meaning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.unitofmeaning')),
            ],
        ),
        migrations.DeleteModel(
            name='Artifact',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
