# Generated by Django 5.2.1 on 2025-06-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_remove_template_creator_remove_template_derived_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitofmeaning',
            name='based_on_meaning',
            field=models.TextField(default='', unique=True),
            preserve_default=False,
        ),
    ]
