# Generated by Django 5.2.1 on 2025-06-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_unitofmeaning_based_on_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='unitofmeaning',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
