# Generated by Django 5.2.1 on 2025-06-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_language_updated_at_learninggoal_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='creation_context',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='translation',
            name='license',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='owner_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='source_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
